// BrandZaha — blog posts (shell entries).
export const posts = [
  { slug: 'why-website-speed-sells', title: 'Why website speed is your best salesperson', excerpt: 'A one-second delay can cost you conversions. How we build sites that load before your visitor blinks — and why it pays off.', category: 'Web Development', date: '2026-01-18', author: 'Himanshi Shrivastav', palette: ['#12130c', '#2a2f16', '#d8ff36'] },
  { slug: 'branding-that-actually-converts', title: 'Branding that actually converts', excerpt: 'Great branding isn’t just looking good — it’s a system that earns trust and drives action. Field notes from real projects.', category: 'Branding', date: '2025-12-02', author: 'Aarav Mehta', palette: ['#0f1114', '#241a2c', '#c79bff'] },
  { slug: 'local-seo-jaipur-playbook', title: 'The local SEO playbook for Jaipur businesses', excerpt: 'How local businesses in Jaipur can climb search results with a focused, honest SEO strategy.', category: 'Digital Marketing', date: '2025-11-10', author: 'Karan Singh', palette: ['#0a0f14', '#12303f', '#8ad7ff'] },
  { slug: 'ai-agents-for-business', title: 'AI agents every business should be using in 2026', excerpt: 'Chatbots and voice agents aren’t hype anymore — they’re quietly closing sales and cutting support costs. Here’s how.', category: 'AI', date: '2026-01-05', author: 'Neha Gupta', palette: ['#0d0f0e', '#16302a', '#5cffce'] },
  { slug: 'designing-for-thumbs', title: 'Designing for thumbs: mobile-first, really', excerpt: 'Most “mobile-friendly” sites are desktop sites squeezed small. What designing genuinely mobile-first looks like.', category: 'UI / UX', date: '2025-10-04', author: 'Isha Verma', palette: ['#120d08', '#3a2410', '#ffb35c'] },
  { slug: 'from-brief-to-launch', title: 'From brief to launch: how a project really flows', excerpt: 'A transparent look at how a BrandZaha project moves from first call to go-live.', category: 'Studio', date: '2025-08-20', author: 'Himanshi Shrivastav', palette: ['#12130c', '#2a2f16', '#d8ff36'] },
];
export default posts;
